name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: boost
      run: sudo apt-get update && sudo apt-get install -yq libboost-test-dev
    - name: arduino version
      run: export ARDUINO_IDE_VERSION="1.8.13"
    - name: teensyduino version
      run: export TEENSYDUINO_IDE_VERSION="153"
    - name: download arduino
      run: wget --quiet https://downloads.arduino.cc/arduino-$ARDUINO_IDE_VERSION-linux64.tar.xz
    - name: print home directory
      run: echo $HOME
    - name: make dir arduino_ido
      run: mkdir $HOME/arduino_ide
    - name: unzip arduino
      run: tar xf arduino-$ARDUINO_IDE_VERSION-linux64.tar.xz -C $HOME/arduino_ide/ 
    - name: download teensyduino
      run: curl -fsSL https://www.pjrc.com/teensy/td_$TEENSYDUINO_IDE_VERSION/TeensyduinoInstall.linux64 -o TeensyduinoInstall.linux64
    - name: make teensyduino executable
      run: chmod +x TeensyduinoInstall.linux64
    - name: run xvfb framebuffer so arduino doesn't die
      run: /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16
    - name: wait for framebuffer
      run: sleep 3
    - name: set xwindows display, workaround to get teensyduino working
      run: export DISPLAY=:1.0
    - name: install teensyduino
      run: ./TeensyduinoInstall.linux64 --dir=$HOME/arduino_ide/arduino-$ARDUINO_IDE_VERSION
    - name: build
      run: ./build.sh
    - name: test
      run: ./test.sh
