name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: boost
      run: sudo apt-get update && sudo apt-get install -yq libboost-test-dev
    - name: install dependencies
      run: |
        export ARDUINO_IDE_VERSION="1.8.13"
        export TEENSYDUINO_IDE_VERSION="153"
        wget --quiet https://downloads.arduino.cc/arduino-$ARDUINO_IDE_VERSION-linux64.tar.xz
        mkdir $HOME/arduino_ide
        tar xf arduino-$ARDUINO_IDE_VERSION-linux64.tar.xz -C $HOME/arduino_ide/ 
        curl -fsSL https://www.pjrc.com/teensy/td_$TEENSYDUINO_IDE_VERSION/TeensyduinoInstall.linux64 -o TeensyduinoInstall.linux64
        chmod +x TeensyduinoInstall.linux64
        /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16
        sleep 3
        export DISPLAY=:1.0
        ./TeensyduinoInstall.linux64 --dir=$HOME/arduino_ide/arduino-$ARDUINO_IDE_VERSION
    - name: build
      run: ./build.sh
    - name: test
      run: ./test.sh
