name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: boost
      run: sudo apt-get update && sudo apt-get install -yq libboost-test-dev
    - name: download arduino
      run: wget https://downloads.arduino.cc/arduino-$ARDUINO_IDE_VERSION-linux64.tar.xz
      env:
        ARDUINO_IDE_VERSION: 1.8.13
    - name: print home directory
      run: echo $HOME
    - name: make dir arduino_ido
      run: mkdir $HOME/arduino_ide
    - name: unzip arduino
      run: tar xf arduino-$ARDUINO_IDE_VERSION-linux64.tar.xz -C $HOME/arduino_ide/ 
      env:
        ARDUINO_IDE_VERSION: 1.8.13
    - name: download teensyduino
      run: curl -fsSL https://www.pjrc.com/teensy/td_$TEENSYDUINO_IDE_VERSION/TeensyduinoInstall.linux64 -o TeensyduinoInstall.linux64
      env:
        TEENSYDUINO_IDE_VERSION: 153         
    - name: make teensyduino executable
      run: chmod +x TeensyduinoInstall.linux64
    - name: install teensyduino
      run: ./TeensyduinoInstall.linux64 --dir=$HOME/arduino_ide/arduino-$ARDUINO_IDE_VERSION
      env:
        ARDUINO_IDE_VERSION: 1.8.13
    - name: build
      run: ./build.sh
    - name: test
      run: ./test.sh
